### ISSUE TITLE
JMeter results directory not found error

### ISSUE THREAD

**Issue by d-dodda** [Azure-Samples/azure-search-performance-testing#7]
Getting below error at jmeter results convert step when I use lod test yaml pipeline script -( [azure-search-performance-testing](https://github.com/Azure-Samples/azure-search-performance-testing/tree/main)/[pipelines](https://github.com/Azure-Samples/azure-search-performance-testing/tree/main/pipelines)
/azure-pipelines.load-test.yml )

Here is the error log - 

---------------------------------------------------------------------------------------------------------------------------------------------
Starting: RESULTS: Convert JMeter Results to JUnit Format
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.231.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/bb347353-e24e-4854-b090-f7bda3b155ae.sh
Converting...
Traceback (most recent call last):
  File "/home/vsts/work/1/s/terraform/../scripts/jtl_junit_converter.py", line 179, in <module>
    main()
  File "/home/vsts/work/1/s/terraform/../scripts/jtl_junit_converter.py", line 173, in main
    test_suites = create_test_suites(sys.argv[1])
  File "/home/vsts/work/1/s/terraform/../scripts/jtl_junit_converter.py", line 164, in create_test_suites
    junit_results = create_junit_results(jtl_results_filename)
  File "/home/vsts/work/1/s/terraform/../scripts/jtl_junit_converter.py", line 106, in create_junit_results
    with open(jtl_results_filename) as jmeter_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vsts/work/1/s/results/results.jtl'

##[error]Bash exited with code '1'.
Finishing: RESULTS: Convert JMeter Results to JUnit Format
----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by sanketsultan** [comment]
Hi @microsoftopensource! I would like to work on this issue. Could you please assign it to me? I believe I can contribute to its resolution effectively. Thanks!

**Comment by ansif-mhmd** [comment]
Same issue. Please update the deck or share the solution. @microsoftopensource

**Comment by ansif-mhmd** [comment]
@microsoftopensource team,

The results.jtl file, which was required by the jtl_junit_converter.py script, was not present in the storage account. As a result, the az storage file download-batch command was unable to download the test results.

![image](https://github.com/user-attachments/assets/2963af2c-c730-4365-8298-8e0cf47f08b1)


Furthermore, the jmeter.log revealed errors that suggested potential issues with the container's network connection, which possibly indicated that the tests could not have been executed as intended:

2024-08-15 09:15:03,250 INFO o.a.j.e.DistributedRunner: Configuring remote engine: 10.0.0.4
2024-08-15 09:15:03,256 INFO o.a.j.r.RmiUtils: Disabling SSL for RMI as server.rmi.ssl.disable is set to 'true'
2024-08-15 09:15:03,326 ERROR o.a.j.e.DistributedRunner: Failed to create engine at 10.0.0.4
java.rmi.ConnectException: Connection refused to host: 10.0.0.4; nested exception is:
java.net.ConnectException: Connection refused (Connection refused)
...
2024-08-15 09:15:03,342 ERROR o.a.j.u.JMeterUtils: Connection refused to host: 10.0.0.4; nested exception is:
java.net.ConnectException: Connection refused (Connection refused)
2024-08-15 09:15:03,342 INFO o.a.j.e.DistributedRunner: Failed to configure 10.0.0.4
2024-08-15 09:15:03,344 INFO o.a.j.e.DistributedRunner: Stopping remote engines
2024-08-15 09:15:03,344 INFO o.a.j.e.DistributedRunner: Remote engines have been stopped
2024-08-15 09:15:03,345 ERROR o.a.j.JMeter: Error in NonGUIDriver
java.lang.RuntimeException: Following remote engines could not be configured:[10.0.0.4]
...
2024-08-15 09:15:03,348 ERROR o.a.j.JMeter: An error occurred:
org.apache.jmeter.report.config.ConfigurationException: Error in NonGUIDriver Followi
